configs {
  key: "medical-ai-course-materials"
  value {
    requirement {
      cpu: 4
      memory: 8
      image: "docker"
    }
    time_limit {
      seconds: 1800
    }
    command:
      "docker run -v $PWD:/medical --rm -t mitmul/medical-ai-course-materials bash -c 'cd /medical && bash build.sh'\n"
      "docker run --rm -t mitmul/medical-ai-course-materials 'GH_TOKEN=$GH_TOKEN bash deploy.sh'\n"
  }
}
