configs {
  key: "medical-ai-course-materials.build"
  value {
    requirement {
      cpu: 4
      memory: 8
      image: "mitmul/medical-ai-course-materials"
    }
    time_limit {
      seconds: 1800
    }
    command: "ls -la"
  }
}
