configs {
  key: "medical-ai.build"
  value {
    requirement {
      cpu: 4
      memory: 8
      image: "docker"
    }
    time_limit {
      seconds: 1800
    }
    command:
      "docker run -v $PWD/build.sh:/build.sh --rm -t mitmul/medical-ai-course-materials:build bash build.sh && doccker run -v $PWD/deploy.sh:/deploy.sh -e GH_TOKEN=$GH_TOKEN --rm -t mitmul/medical-ai-course-materials:build bash deploy.sh\n"
  }
}
